package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build_2'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build_2")) {
    check(name == "Build (1)") {
        "Unexpected name: '$name'"
    }
    name = "Test"
}
