name: Java CI with Gradle

on: [pull_request]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        java: [ '8', '11', '13', '15' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.0.1
      with:
        arguments: bootJar
